name: fhir_surveys

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fhir: ^0.4.6
  flutter:
    sdk: flutter
  get: ^4.1.4
  percent_indicator: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter