name: fhir_surveys
version: 0.3.0-nullsafety.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  fhir: ^0.3.0-nullsafety.0
  flutter:
    sdk: flutter
  get: ^4.0.0-nullsafety.2
  percent_indicator: ^3.3.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter